language: android

sudo: false

env:
  global:
      - ANDROID_BUILD_TOOLS_VERSION=28.0.3
      - ADB_INSTALL_TIMEOUT=10

  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a

android:
  components:

    # Use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools

    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - $ANDROID_TARGET
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify the system image to run emulator during tests
    - sys-img-$ANDROID_ABI-$ANDROID_TARGET

  licenses:
      - 'android-sdk-preview-license-52d11cd2'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

jdk:
  - oraclejdk8

os:
  - linux

before_script:
  - pip install --user codecov

script:
  - ./gradlew build test

after_success:
  - bash <(curl -s https://codecov.io/bash)
